# The URL the site will be built for
#base_url = "https://salaheddineghamri.github.io/posts"
base_url = ""

compile_sass = true
title = "odd theme"
description = "A theme for my portfolio website"
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Salah Eddine Ghamri"

odd_menu = [
    {url = "$BASE_URL", name = "Main"},
]

odd_title = ""
