name = "odd"
description = "a theme for my personal blog"
license = "MIT"
homepage = "https://github.com/salaheddineghamri/odd"
min_version = "0.1.0"
demo = ""

[extra]
odd_menu = [
    {url = "$BASE_URL", name = "Return to main"},
]
odd_title = ""

[author]
name = "Salah Eddine Ghamri"
homepage = ""
